hy: 
ssh: C:\Users\Administrator\.ssh\id_rsa
shop:
    driverClassName: com.mysql.cj.jdbc.Driver
    driverVersion: 8.0.23
    password: axDvgYjIlk1!
    url: jdbc:mysql://156.224.19.162:3306/sgshop?useSSL=false&allowPublicKeyRetrieval=true
    username: youruser
    ip: 156.224.19.162:3306
    dbName: sgshop
    dbaMobile: 15907658484
    dbaName: 吴肖均
    dbaEmail: sasha@sellgirl.commm